### PR TITLE
Add jest plugin and settings

### PR DESCRIPTION
**Pull request by weltenwort**
This extracts the ui-specific eslint settings from elastic/kibana so they can
be applied to other repositories as well.

### CODE REVIEW

**Review by kimjoar — APPROVED** [review]

**Comment by kimjoar** [comment]
When this is merged, can you push a new version and create PRs for core and xpack?

**Comment by spalger** [comment]
I use the kibana presets in non-kibana projects that I really don't want to depend on jest. Can we add this as a supplementary config that needs opt-in via extends?

if it exposed a `jest.js` file at the root of the package this should work:

```yaml
---
extends:
  - "@elastic/kibana"
  - "@elastic/kibana/jest"
```

**Comment by kimjoar** [comment]
-1 from me. imo this is the _Kibana_ eslint config, and should be optimized for those projects (It's not a big deal, but we shouldn't have to think about this when adding other plugins later either imo)

**Comment by kimjoar** [comment]
(Though, maybe it makes sense if there are other elastic projects that rely on them but not jest? Open to the idea)

**Comment by spalger** [comment]
> (Though, maybe it makes sense if there are other elastic projects that rely on them but not jest? Open to the idea)

That's what I'm describing, other elastic js projects that reuse the kibana config but aren't using jest. We can improve that after this is merged though, LGTM

**Comment by kimjoar** [comment]
Ah, I misunderstood the "non-kibana projects" part. Works for me.

**Comment by weltenwort** [comment]
@spalger makes sense, thanks for the suggestion. I updated the PR.

**Comment by weltenwort** [comment]
When adding some documentation I noticed that we are referencing the config as `@elastic/kibana` in Kibana's root `.eslintrc` even though the [documentation](http://eslint.org/docs/developer-guide/shareable-configs#npm-scoped-modules) states:

> The module name can also be customized, just note that when using scoped modules it is not possible to omit the `eslint-config-` prefix. Doing so would result in package naming conflicts, and thus in resolution errors in most of cases.

Is that something we want to change as well to align with the official docs?

**Comment by spalger** [comment]
@weltenwort if it works in eslint 3 then I think we should, but pretty sure that was a breaking change added in eslint 4

**Comment by weltenwort** [comment]
I think specifying the fully qualified name was always supported. There was a breaking change in 4 that disallows shorthands in namespaced packages to fix misbehavior resulting from ambiguities. I will change it in the PR that references this in kibana after this is merged and published.

@spalger any other concerns?

**Comment by weltenwort** [comment]
replaced by elastic/kibana#13090

**Pull request closed without merging**
